### ISSUE TITLE
New Jellyfin update broke skins

### ISSUE THREAD

**Issue by Otouq** [danieladov/jellyfin-plugin-skin-manager#66]
after the new update, the skins made jellyfin kinda broken.. 
Im not sure if this is only me, but it's been happening ever since. I disabled the skin and it looks normal, but whenever i try to enable it back again it goes like that.
![image](https://github.com/danieladov/jellyfin-plugin-skin-manager/assets/88352634/8902be1a-568d-4d8e-a128-0896abca8b35)

**Comment by tanmoumou252** [comment]
Use Firefox and Chrome's new privacy tabs to open web pages to retest, or clear cookies

The essence of this plugin is to write custom CSS to the dashboard   
![图片](https://github.com/danieladov/jellyfin-plugin-skin-manager/assets/118299342/1c37df42-28ea-451c-9b0b-390b8fc777e9)

**Comment by Namo2** [comment]
Which skin are you using?
I can probably rewrite the css real quick

You can set the custom css yourself under Home -> Dashboard -> General.
I use this for Kaleidochromic:
```css

@import url('https://ctalvio.github.io/Kaleidochromic/default_style.css');:root {--accent: 98.00787045,121.00999580324999,204.99450000000002;}
:root {--rounding: 12px;}
.page {
  height: 100vh;
}

```
So far it works for me
