### ISSUE TITLE
Jellyskin theme broke after the update

### ISSUE THREAD

**Issue by omarashraf307** [danieladov/jellyfin-plugin-skin-manager#67]
The skins are broken now after the last update

**Comment by Namo2** [comment]
Have a look at #66

**Comment by omarashraf307** [comment]
This is how the jellyskin looks like after the update

![image](https://github.com/danieladov/jellyfin-plugin-skin-manager/assets/77493619/4a2212ea-00e6-474a-bf8c-524aa470b210)

and if you tried to scroll down you will find that you can only scroll in that small section up there.
The rest of the page is empty but you can scroll in that very small area
<img width="807" alt="image" src="https://github.com/danieladov/jellyfin-plugin-skin-manager/assets/77493619/b83ace9a-d0e2-459f-9d22-96ee20e44b26">

**Comment by omarashraf307** [comment]
Also this is how the dashboard page looks like now.
<img width="943" alt="image" src="https://github.com/danieladov/jellyfin-plugin-skin-manager/assets/77493619/8e9dc027-ae94-4dd2-b9df-fb840c461f07">

**Comment by Namo2** [comment]
I guess in the meantime, you can use this:

```css

@import url('https://cdn.jsdelivr.net/gh/prayag17/JellySkin/default.css');
@import url('https://cdn.jsdelivr.net/npm/jellyskin@latest/dist/main.css');
.content-primary {
  margin-left: 260px;
}
.mainAnimatedPages.skinBody {
  height: 100vh;
}

```
