### ISSUE TITLE
Add custom CSS

### ISSUE THREAD

**Issue by Mars160** [danieladov/jellyfin-plugin-skin-manager#77]
Thank you so much for your team, it's a great plugin.
I have a small request, it would be cool if you could add custom css code to an existing theme.
For example, I like the Ultrachromic theme, but I'm not particularly satisfied with it not expanding my media library, so I need to manually add the following code in the jellyfin settings.

```css
@media all and (min-width: 00em) { .homePage .emby-scroller { margin-right: 0; } .homePage .emby-scrollbuttons { display: none; } .homePage .itemsContainer { align-items: center; flex-wrap: wrap; } }
```

But whenever I use your plugin to modify the theme, my custom css will be **overwritten**, causing my edits to be lost.
So I wonder if it is possible to add custom css functionality to your plugin so that I can **add custom css in the plugin** without worrying about it being overwritten.

My English is poor so I used Google Translate. Hope it doesn't make any trouble to you!
